# BIBLIOTECA NUMPY
* Biblioteca baseada em estruturas de **arrays** (*estrutura de dados multidimensional*);
* Trabalha com arrays de N-dimensões (traz uma série de vantagens pois é uma estrutura de dados mais eficiente);
* Indicada para manipulação de dados | cálculos matemáticos;
* **Vantagens:** eficiência e versatilidade em trabalhar com dados.

* **ESTRUTURA DE ARRAYS:**

In [6]:
# Analise de desempenho das listas em Python nativo
from time import time
inicio = time()

lista_1 = list(range(0, 10**7))
soma_1 = 0
for i in lista_1:
    soma_1 += i
fim = time()
tempo_1 = fim - inicio 

print(f"Soma dos valores: {soma_1}")
print(f"Tempo de execução: {tempo_1}")

Soma dos valores: 49999995000000
Tempo de execução: 0.9325351715087891


In [7]:
# Analise de desempenho da biblioteca numpy
import numpy as np
inicio = time()

array = np.array(lista_1, dtype=float)   # estrutura de dados especifica da biblioteca numpy
soma_2 = array.sum()

fim = time()
tempo_2 = fim - inicio

print(f"Soma dos valores: {soma_2}")
print(f"Tempo de execução: {tempo_2}")

Soma dos valores: 49999995000000.0
Tempo de execução: 0.4104580879211426


In [5]:
print(f"Razão do tempo: {tempo_1 / tempo_2}")

Razão do tempo: 2.4675438596491226


- **ARRAYS NUMPY:**
  * Propriedades dos arrays:
    * **ndim**: retorna (int) o número de dimensões (axes);
    * **shape**: retorna (tupla) a quantidade de dados em cada dimensão;
    * **size**: retorna (int) o número de elementos;
    * **dtype**: retorna (dtype) o tipo das variáveis dos elementos.
    

In [24]:
import numpy as np

a1 = np.array([1, 1, 1], dtype=float)
a1.shape
a1.size
a1.ndim
a1.dtype

dtype('float64')

In [25]:
a2 = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
a2.shape
a2.size
a2.ndim
a2.dtype

dtype('float64')

In [31]:
a3 = np.arange(27).reshape(3, 3, 3)
a3
a4 = np.arange(40).reshape(2, 2, 2, 5)
a4
a4.shape
a4.ndim
a4.dtype

dtype('int32')

- **OPERAÇÕES COM ARRAYS:**
  * sin, cos, exp, sqrt: funções seno, cosseno, exponencial, raiz quadrada;
  * pi, nan, inf: constantes(float) pi, similar ao None, infinito;
  * +, -, *, /: operações aritméticas;
  * ARRAY1.dot(ARRAY2): método (multiplicação matricial).

In [42]:
import numpy as np

np.pi
np.sin(np.pi)
np.cos(np.pi)
np.exp(np.pi)
np.sqrt(np.pi)
np.inf
np.nan

nan

In [51]:
a1 = np.array([[1, 2, 3]])
a2 = np.array([[4, 5, 6]])
a1 + a2
a1 - a2
a1 * a2      # multiplicacao elemento a elemento

a2 = np.array([4, 5, 6])
a1.dot(a2)   # multiplicacao de matrizes no numpy

array([32])

- **CRIAÇÃO DE ARRAYS:**
  * **Funções:**
    * zeros(shape): array preenchido com 0s;
    * ones(shape): array preenchido com 1s;
    * eye(dimensao): matriz identidade;
    * arange(inicio, fim, passo): cria um array unidimensional;
    * linspace(inicio, fim, quantidade): cria um array unidimensional;
    * vstack((arrays)) e hstack((arrays)): adiciona elementos de um ou mais arrays.
  * **Métodos:**
    * reshape: retorna um array com o shape indicado;
    * resize: modifica o shape do array em que está sendo aplicado.

In [2]:
import numpy as np

a1 = np.zeros(6)
a1
a2 = np.ones(6) * 10
a2
a3 = np.eye(4)
a3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
a4 = np.arange(0, 10, 0.5)
a4
a5 = np.linspace(0, 10, 12)
a5

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [8]:
a6 = np.ones(8)
a6
a6.reshape(2, 4)   # não modifica a estrutura o array original
a6
a6.resize(2, 4)    # modifica a estrutura do array original
a6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
a0 = np.zeros(8)
a0.resize(2, 4)
a1 = np.ones(8)
a1.resize(2, 4)

av = np.vstack((a0, a1))
av
ah = np.hstack((a0, a1))
ah

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

- **MÉTODO copy():**
  Faz a cópia (deep copy) do array. Cuidado! O sinal de igual não executa essa função. Nota: a propriedade base retorna o array utilizado para criar o array em questão.

  **OBS**: *array é um objeto e possui um método específico para ser copiado como uma variável independente:* .copy()

In [12]:
import numpy as np
a = np.arange(8)
a
b = a   # o mesmo array e adiconado em outra variavel. Eles possuem relacao como pode ser visto abaixo
b
a[0] = 100
a
b
a is b

True

In [27]:
a[0] = 9
a
c = a.copy()
a[0] = 1
a
c
c is a

False

In [31]:
a
d = a.reshape(2, 4)
d
d is a
d.base is a

True

- **MÉTODOS MATEMÁTICOS PARA ARRAYS:**

  * .max() | .min(): retorna os valores máximo e mínimo;
  * .argmax() | .argmin(): retorna os índices de valor máximo e mínimo;
  * .sum() | .mean() | .std(): soma, média e desvio-padrão;
  * .cumsum(): retorna um array com a soma acumulada.

In [47]:
import numpy as np
arr = np.arange(8).reshape(2,4)**2
arr[0][0] = 11 
arr.max()
arr.max(axis=1)
arr.min()
arr.argmax()
arr.argmin()
arr.sum()
arr.mean()
arr.std()
arr.cumsum()

array([ 11,  12,  16,  25,  41,  66, 102, 151])

- **ÍNDICES E FATIAS DE ARRAYS:**

  * [i]: para 1 dimensão funciona como nas listas;
  * [:i]: exibe um array que vai do índice 0 até o anterior ao i;
  * [i:]: exibe um array que vai do índice posterior ao i até o último índice;
  * [::i]: exibe todos os elementos variando de i em i;
  * [::-i]: exibe a sequência de elementos de trás para frente variando de i em i;
  * [a:b:c]: início, fim, step;
  * [i,j]: para exibir um elemento de uma matriz;
  * [i,a:b]: retorna uma fatia da linha i com elementos das colunas a até b;
  * [n,i,j]: outra dimensão, linha, coluna.

In [15]:
import numpy as np

# Arrays unidimensionais
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [17]:
a[len(a) - 1]
a[:2]
a[2:]
a[::3]
a[::-2]
a[2:8:2]

array([ 4, 16, 36])

In [18]:
# Arrays bidimensionais
b = np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
b[1,1]
b[0,:5]
b[:4,0]
b[1,2:]
b[2:,3:]

array([[13, 14],
       [18, 19]])

In [29]:
c = np.arange(40).reshape(2,4,5)
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [31]:
c[1,1,1]

26

- **OPERAÇÕES COM VETORES E MATRIZES NO NUMPY:**

  * .dot(**a**,**b**) ou @: retorna o **produto escalar** entre os vetores **a** e **b**;
  * .cross(**a**,**b**): retorna o **produto vetorial** entre os vetores **a** e **b**;
  * .inner(**a**,**b**) e .outer(**a**,**b**): retorna o **produto interno** e **externo** entre os vetores **a** e **b**;
  * .linalg.norm(**a**): retorna a **norma** do vetor **a**;
  * .matmul(**A**,**B**) ou @: retorna o **produto** entre as matrizes **A** e **B**;
  * .linalg.det(**A**): retorna o **determinante** da matriz **A**;
  * .linalg.inv(**A**): retorna a **matriz inversa** de **A**.

**Operações com vetores:**

In [36]:
import numpy as np

a = np.array([1, 2, 3])
np.dot(a,a)
a@a

14

In [46]:
np.inner(a,a)
np.outer(a,a)
np.cross(np.array([1,0,0]), np.array([0,1,0]))

array([0, 0, 1])

In [45]:
a
np.sqrt(1**2 + 2**2 + 3**2)
np.linalg.norm(a)
np.linalg.norm(a) == np.sqrt(1**2 + 2**2 + 3**2)

True

**Operações com matrizes:**

In [54]:
A = np.array([[1,2],[4,4]])
np.matmul(A,A)
A@A
np.linalg.det(A)
np.linalg.inv(A)
np.matmul(A, np.linalg.inv(A))

array([[1., 0.],
       [0., 1.]])

**Autovalor e Autovetor:**

  * .linalg.eig(**A**): retorna os autovalores e autovetores da matriz **A**.

In [65]:
import numpy as np

A = np.array([[5,3,-1], [3,4,0], [-1,0,2]])
(eigenvalues, eigenvectors) = np.linalg.eig(A)
print(f"Autovalores: {eigenvalues}")
print("==========")
print(f"Autovetores: {eigenvectors}")

Autovalores: [7.64575131 1.         2.35424869]
Autovetores: [[-0.76505532 -0.57735027 -0.28523152]
 [-0.6295454   0.57735027  0.51994159]
 [ 0.13550992 -0.57735027  0.8051731 ]]


**Solver para sistemas lineares:**

 * .linalg.solve(A,B): resolve um sistema linear do tipo AX = B.

In [67]:
import numpy as np

A = np.array([[3,-1,1],
              [-2,3,-3],
              [-1,-3,-4]])

B = np.array([11,-19,-15])
solucao = np.linalg.solve(A,B)
solucao

array([ 2., -1.,  4.])

In [71]:
A = np.array([
                [1,1,1],
                [1,2,2],
                [2,1,3]
            ])

B = np.array([6,9,11])
solucao = np.linalg.solve(A,B)
solucao

array([3., 2., 1.])