In [1]:
# Bibliotecas
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [2]:
# Dataset
dataset = pd.read_csv("startups.csv")
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,4].values

In [3]:
# Codificando a variável categórica de estado
columnTransformer = ColumnTransformer([("encoder", OneHotEncoder(), [3])], remainder="passthrough")
X = np.array(columnTransformer.fit_transform(X), dtype=np.float64)
X = X[:,1:]

In [4]:
# Divisão do dataset em treino e teste
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [5]:
# Regressão linear múltipla
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [6]:
# Predição
Y_pred = regressor.predict(X_test)
for k in range(len(Y_test)):
  Y_teste = Y_test[k]
  Y_previsto = Y_pred[k]
  erro = abs((Y_test[k] - Y_pred[k]) / Y_pred[k] * 100)
  print(f"Y_test: {Y_teste:.2f}. Y_previsto: {Y_previsto:.2f}. Erro: {erro:.2f}")

Y_test: 103282.38. Y_previsto: 103015.20. Erro: 0.26
Y_test: 144259.40. Y_previsto: 132582.28. Erro: 8.81
Y_test: 146121.95. Y_previsto: 132447.74. Erro: 10.32
Y_test: 77798.83. Y_previsto: 71976.10. Erro: 8.09
Y_test: 191050.39. Y_previsto: 178537.48. Erro: 7.01
Y_test: 105008.31. Y_previsto: 116161.24. Erro: 9.60
Y_test: 81229.06. Y_previsto: 67851.69. Erro: 19.72
Y_test: 97483.56. Y_previsto: 98791.73. Erro: 1.32
Y_test: 110352.25. Y_previsto: 113969.44. Erro: 3.17
Y_test: 166187.94. Y_previsto: 167921.07. Erro: 1.03


In [7]:
# Verificando a significância estatística das variáveis
X_opt = X[:,[0, 1, 2, 3, 4]]
regressor_OLS = sm.OLS(Y, X_opt).fit()
regressor_OLS.summary()
regressor_OLS.pvalues

array([4.32872717e-01, 1.96913258e-01, 1.92850743e-10, 1.94845691e-14,
       1.43225732e-03])

In [8]:
# Verificando a significância estatística das variáveis
X_opt = X[:,[2, 3, 4]]
regressor_OLS = sm.OLS(Y, X_opt).fit()
regressor_OLS.summary()
regressor_OLS.pvalues

array([7.39083224e-14, 1.16808458e-14, 5.10773483e-04])

In [9]:
# Verificando a significância estatística das variáveis
X_opt = X[:,[2, 3]]
regressor_OLS = sm.OLS(Y, X_opt).fit()
regressor_OLS.summary()
regressor_OLS.pvalues

array([7.33006903e-14, 3.33897094e-23])