# BIBLIOTECA NUMPY

## Importar Biblioteca

In [2]:
import numpy as np

## Gerar Dados Aleatórios

In [3]:
dados = np.random.rand(2,3)
dados

array([[0.98109692, 0.59391166, 0.11689017],
       [0.07529328, 0.19530032, 0.60988318]])

## Tipo do Array

In [6]:
dados.dtype

dtype('float64')

## Tamanho e Quantidade de Dimensões

In [7]:
dados.shape

(2, 3)

In [9]:
dados.ndim

2

## Criar ndarray Usando a Função Array
Ao criar o array a função array tenta utilizar o melhor tipo de dados

In [10]:
lista = [1, 2, 5, 7.8, 1.25]   # estrutura nativa do python
dados2 = np.array(lista)
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

In [12]:
lista2 = [[1, 2, 3, 4],[4, 3, 2, 1]]   # estrutura nativa do python
dados3 = np.array(lista2)
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

## Outras Maneiras de Criar Arrays

In [13]:
dadosZero = np.zeros(10)
dadosZero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
dadosZero2 = np.zeros((2,3))
dadosZero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
dadosUm = np.ones(10)
dadosUm

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
dadosUm2 = np.ones((2,3))
dadosUm2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
dadosSeq = np.arange(10)
dadosSeq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
dadosSeq2 = np.arange(0,20,2)
dadosSeq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
dadosSeq2.dtype

dtype('int64')

In [21]:
dadosSeqFloat = dadosSeq.astype(np.float64)
dadosSeqFloat.dtype

dtype('float64')

## Aritmética com Arrays

In [22]:
dados4 = np.array([[1, 2, 3],[4, 5, 6]])
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
dados4 * dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [24]:
dados4 - dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
1 / dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [27]:
dados5 = dados4 + dados4
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [28]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

## Indexação

In [29]:
dadosSeq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
dadosSeq[5]

5

In [31]:
dadosSeq[3:6]

array([3, 4, 5])

In [32]:
dadosSeq[3:6] = 20
dadosSeq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [33]:
fatiaDados = dadosSeq[3:6]
fatiaDados

array([20, 20, 20])

## Copiar Dados

In [35]:
fatia2 = dadosSeq[2:4].copy()
fatia2

array([ 2, 20])

In [37]:
fatia2[:] = 100
fatia2
dadosSeq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

## Array Com Mais de Uma Dimensão

In [39]:
dados6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
dados6[1,2]

6

## Máscaras

In [43]:
dadosSeq = np.array([0, 1, 333, 333, 20, 20, 6, 7, 8, 9])
dadosSeq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [46]:
mascara = (dadosSeq < 100)
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [48]:
dadosSeq[dadosSeq < 20] = 888
dadosSeq

array([888, 888, 333, 333,  20,  20, 888, 888, 888, 888])

## Transposição

In [57]:
dados7 = np.arange(15)
dados7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
dados8 = dados7.reshape((3,5))
dados8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
dados8.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [63]:
dados10 = np.arange(4)
dados10

array([0, 1, 2, 3])

In [64]:
dados10.T

array([0, 1, 2, 3])

In [66]:
dados10.reshape((2,2))

array([[0, 1],
       [2, 3]])

In [67]:
dados10.reshape((2,2)).T

array([[0, 2],
       [1, 3]])

In [68]:
np.dot(dados10, dados10.T)

14

In [69]:
np.dot(dados10.T, dados10)

14