In [12]:
import numpy as np

scalar = np.array(100)
vector = np.array([100, 200, 300])
matrix = np.array([[10, 20, 30], [100, 200, 300]])

print("Escalar no Numpy")
print(scalar, type(scalar))
print("Vetor no Numpy")
print(vector, type(vector))
print("Matriz no Numpy")
print(matrix, type(matrix))
print("")

print("Dimensões no Numpy")
print(scalar.shape)
print(vector.shape)
print(matrix.shape)
print("")

print("Transposição no Numpy")
vectorT = vector.reshape(3,1)
print(vectorT, vectorT.shape)
matrixT = matrix.reshape(3,2)
print(matrixT, matrixT.shape)

Escalar no Numpy
100 <class 'numpy.ndarray'>
Vetor no Numpy
[100 200 300] <class 'numpy.ndarray'>
Matriz no Numpy
[[ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'>

Dimensões no Numpy
()
(3,)
(2, 3)

Transposição no Numpy
[[100]
 [200]
 [300]] (3, 1)
[[ 10  20]
 [ 30 100]
 [200 300]] (3, 2)
