# BIBLIOTECA SCIPY

* A construção do *scipy* é baseada no *numpy*;
* Biblioteca "mais moderna" que a *numpy*;
* Biblioteca útil para problemas que necessitam de **soluções numéricas**;

- **FUNÇÕES PARA ÁLGEBRA LINEAR:**

  * **Referência:** *https://docs.scipy.org/doc/scipy/reference/*
  * ```python
    from scipy import linalg
    ```
  * **Funcionalidades:**
    * linalg.inv(arg): retorna a inversa de uma matriz;
    * linalg.det(arg): retorna o determinante de uma matriz;
    * linalg.norm(arg): retorna a norma de um vetor;
    * linalg.solve(arg): resolve um sistema linear;
    * linalg.eig(arg): retorna os autovalores e autovetores.

In [12]:
from scipy import linalg
import numpy as np

A = np.array([[1,0,0],[0,5,0],[0,0,9]])
a = np.array([1,2,3])

linalg.inv(A)
linalg.det(A)
linalg.norm(A)
linalg.norm(a) == np.sqrt(np.sum(a**2))

True

**Exercício 1:** Solução

In [35]:
A = np.array([[1,2],
              [4,5]])
linalg.det(A)
A.T
linalg.inv(A)
A@linalg.inv(A)

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

In [36]:
B = np.array([[np.cos(np.pi/4),-np.sin(np.pi/4)], 
              [np.sin(np.pi/4),np.cos(np.pi/4)]])
linalg.det(B)
B.T
linalg.inv(B)
B@linalg.inv(B)

array([[1.00000000e+00, 1.01465364e-17],
       [1.01465364e-17, 1.00000000e+00]])

In [37]:
C = np.array([[2,-2], 
              [-2,5]])
linalg.det(C)
C.T
linalg.inv(C)
C@linalg.inv(C)

array([[1.00000000e+00, 0.00000000e+00],
       [5.55111512e-17, 1.00000000e+00]])

In [38]:
D = np.array([[2,2], 
              [4,4]])
linalg.det(D)
D.T
#linalg.inv(D)
#D@linalg.inv(D)

array([[2, 4],
       [2, 4]])

**Exercício 2:** Solução

In [43]:
A = np.array([[1,1,1],
              [1,2,2],
              [2,1,3]])

B = np.array([6,9,11])

solucao = linalg.solve(A,B)
solucao
A@solucao

array([ 6.,  9., 11.])

**Exercício 3:** Solução

In [56]:
A = np.array([[-1,6],
              [0,5]])
eigenvalues, eigenvectors = linalg.eig(A)
eigenvalues
eigenvector1 = eigenvectors[:,0]
eigenvector2 = eigenvectors[:,1]
eigenvector2

A@eigenvector1 - eigenvalues[0]*eigenvector1
A@eigenvector2 - eigenvalues[1]*eigenvector2

array([0.+0.j, 0.+0.j])